CREATE TABLE [dbo].[professor](
	[Id] [int] NOT NULL,
	[nome] [nchar](100) NOT NULL,
	[prontuario] [nchar](7) NOT NULL,
	[email] [nchar](200) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

-- EXECUTAR UMA PROCEDURE POR UMA SELECIONANDO TODO O CODIGO


CREATE PROCEDURE SP_InserirProfessor
       @ID AS INT,
       @NOME AS VARCHAR(50),
       @PRONTUARIO AS VARCHAR(9),
       @EMAIL AS VARCHAR(50)

  
AS
BEGIN
       INSERT INTO PROFESSOR (ID,NOME,PRONTUARIO,EMAIL) 
       VALUES (@ID, @NOME, @PRONTUARIO, @EMAIL)
END


-- EXECUTAR UMA PROCEDURE POR UMA SELECIONANDO TODO O CODIGO


CREATE PROCEDURE SP_AtualizarProfessor
       @ID AS VARCHAR(50),
       @NOME AS VARCHAR(50),
       @PRONTUARIO AS VARCHAR(9),
       @EMAIL AS VARCHAR(50)

  
AS
BEGIN
       UPDATE TB_PROFESSOR SET NOME=@NOME, PRONTUARIO=@PRONTUARIO, EMAIL=@EMAIL WHERE ID=@ID
END


-- EXECUTAR UMA PROCEDURE POR UMA SELECIONANDO TODO O CODIGO


  
CREATE PROCEDURE SP_ExcluirProfessor
       @ID AS INT
AS
BEGIN
       DELETE FROM TB_PROFESSOR WHERE ID=@ID
END


-- EXECUTAR UMA PROCEDURE POR UMA SELECIONANDO TODO O CODIGO


CREATE PROCEDURE SP_SelecionarProfessor
       @ID AS INT
AS
BEGIN
       SELECT * FROM PROFESSOR WHERE ID=@ID
END